const List<Map<String, String>> opcionesInvito = [
  { 'label': 'SELECCIONA UNA OPCIÓN', 'value': '' },
  { 'label': 'NINGUNO DE LOS ANTERIORES', 'value': 'NINGUNO' },
  { 'label': 'ADRIAN MOLINA', 'value': 'ADRIAN MOLINA' },
  { 'label': 'ALDAHIR GOMEZ', 'value': 'ALDAHIR GOMEZ' },
  { 'label': 'ALEJANDRA RIVAS', 'value': 'ALEJANDRA RIVAS' },
  { 'label': 'ALUMNO', 'value': 'ALUMNO' },
  { 'label': 'ANALIT ROMAN ARCE', 'value': 'ANALIT ROMAN ARCE' },
  { 'label': 'ANALY ORTEGA', 'value': 'ANALY ORTEGA' },
  { 'label': 'ANGELICA NIETO', 'value': 'ANGELICA NIETO' },
  { 'label': 'ASHLEY GONZALEZ', 'value': 'ASHLEY GONZALEZ' },
  { 'label': 'BRYAN MURGA', 'value': 'BRYAN MURGA' },
  { 'label': 'CESAR SANTA OLALLA', 'value': 'CESAR SANTA OLALLA' },
  { 'label': 'CLAUDIA GONZALES', 'value': 'CLAUDIA GONZALES' },
  { 'label': 'ISIS CORTES', 'value': 'ISIS CORTES' },
  { 'label': 'JAVIER ESPINOSA', 'value': 'JAVIER ESPINOSA' },
  { 'label': 'JESUS GUZMAN', 'value': 'JESUS GUZMAN' },
  { 'label': 'JESUS TRILLO', 'value': 'JESUS TRILLO' },
  { 'label': 'KEREN GOMEZ', 'value': 'KEREN GOMEZ' },
  { 'label': 'MARCO SALGADO', 'value': 'MARCO SALGADO' },
  { 'label': 'MELYSSA MONROY', 'value': 'MELYSSA MONROY' },
  { 'label': 'RAUL CASTILLEJA', 'value': 'RAUL CASTILLEJA' },
  { 'label': 'REDES SOCIALES / CORREO', 'value': 'REDES SOCIALES / CORREO' },
  { 'label': 'SARA DURAN', 'value': 'SARA DURAN' },
  { 'label': 'SEBASTIAN RODRIGUEZ', 'value': 'SEBASTIAN RODRIGUEZ' },
  { 'label': 'XIMENA MARTINEZ', 'value': 'XIMENA MARTINEZ' },
  { 'label': 'YANIN VAZQUEZ', 'value': 'YANIN VAZQUEZ' },
];
